services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/web
      - web_node_modules:/web/node_modules
    environment:
      - TZ=Asia/Tokyo
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - VITE_API_PROXY_TARGET=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  web_node_modules:
